#!/bin/bash

# print out the image version
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
BLUE=$(tput bold; tput setaf 4)
ORANGE=$(tput setaf 3)
RESET=$(tput sgr0)

function print_ok() {
  echo "${GREEN}Pass${RESET}"
}
function print_fail() {
  echo "${RED}Fail${RESET}"
}
function print_check() {
  printf "%-60s" "$1"
}
function language_supported() {
  if grep -q "^$1\$" /icpc/supported_languages ; then
    return 0
  fi
  return 1
}
function print_version() {
  language_supported "$1" || return
  print_check "${3:-$1}"
  shift
  VERSION=$($@ 2>&1| grep -Eo '[0-9]+\.[0-9]+(\.[0-9]+)?([_-p][0-9]+)?' |awk '{print length, $0}'|sort -rn |cut -d " " -f2- | head -n1)
  UNKNOWN="${RED}Unknown${RESET}"
  VERSION="${VERSION:-$UNKNOWN}"
  echo $VERSION
}
function print_first_version() {
  language_supported "$1" || return
  print_check "${3:-$1}"
  shift
  VERSION=$($@ 2>&1| grep -Eo '[0-9]+\.[0-9]+(\.[0-9]+)?([_-p][0-9]+)?' | head -n1)
  UNKNOWN="${RED}Unknown${RESET}"
  VERSION="${VERSION:-$UNKNOWN}"
  echo $VERSION
}
function check_return() {
  if [ $1 -eq 0 ]; then
    print_ok
  else
    print_fail
  fi
}
function check_service() {
  systemctl is-active $1 >/dev/null 2>&1
  check_return $?
}

echo "${BLUE}System Configuration${RESET}"
print_check "Team ID"
TEAMNAME="$(cat /icpc/TEAM 2>/dev/null)"
NOTEAM="${RED}Not Set${RESET}"
TEAMNAME="${TEAMNAME:-$NOTEAM}"
echo $TEAMNAME

print_check "Site ID"
SITENAME="$(cat /icpc/SITE 2>/dev/null)"
NOSITE="${RED}Not Set${RESET}"
SITENAME="${SITENAME:-$NOSITE}"
echo $SITENAME

# only check domjudge autologin if there are autologin urls defined
if grep -q 'acl autologin url_regex' /etc/squid/squid.conf ; then
  print_check "DOMjudge Autologin Configured"
  cat /etc/squid/autologin.conf 2>/dev/null | grep "X-DOMjudge" > /dev/null
  if [ $? -eq 0 ]; then
    echo "${GREEN}Yes${RESET}"
    print_check "    Team Login"
    DJTEAM=$(cat /etc/squid/autologin.conf | awk '/X-DOMjudge-Login/{print $3}' | tr -d '"')
    echo $DJTEAM
  else
    echo "${ORANGE}No${RESET}"
  fi
fi

echo
echo "${BLUE}Printing Configuration${RESET}"
print_check "Making sure cups is running"
check_service 'cups'
PRINTERS=$(lpstat -v 2>/dev/null| grep -v ContestPrinter | sed -e 's|socket://||' -e 's|:||' | awk '{printf "    %-56s%s\n", $3, $4}')
NUMPRINTERS=$(echo -n "$PRINTERS" | grep -c Printer)
print_check "Checking there are printers present"
if [ "$NUMPRINTERS" -eq "0" ]; then
  print_fail
else
  print_ok
fi
echo "Configured Printers:"
echo "$PRINTERS"

echo
echo "${BLUE}Connectivity Test${RESET}"
print_check "Checking if the firewall is enabled"
ufw status 2>&1 | grep 'Status: active' >/dev/null
check_return $?


print_check "Making sure the squid proxy is running"
check_service 'squid'

print_check "Testing access to google is blocked with a proxy error"
wget -e use_proxy=yes -e http_proxy=127.0.0.1:3128 -O- http://google.com 2>/dev/null | grep "<h1>Access Denied</h1>" > /dev/null
check_return $?

while IFS="" read -r url ; do
  [ -z "$url" ] && continue
  print_check "Testing access to $url is successful with proxy"
  wget -e use_proxy=yes -T 5 -t 1 -e http_proxy=127.0.0.1:3128 -e https_proxy=127.0.0.1:3128 -O- --no-check-certificate $url 2>/dev/null | grep -i "html" > /dev/null
  check_return $?
  break # only check one url from the list
done < /var/lib/squidguard/db/icpcsites-urllist

while IFS="" read -r url ; do
  [ -z "$url" ] && continue
  print_check "Testing access to http://$url is successful with proxy"
  wget -e use_proxy=yes -T 5 -t 1 -e http_proxy=127.0.0.1:3128 -e https_proxy=127.0.0.1:3128 -O- --no-check-certificate http://$url 2>/dev/null | grep -i "html" > /dev/null
  check_return $?
  break # only check one domain from the list
done < /var/lib/squidguard/db/icpcsites-domainlist


print_check "Testing direct internet access is disabled"
su - contestant -c 'wget -T 5 -t 1 -e use_proxy=no -O- http://google.com >/dev/null 2>&1' 2>/dev/null
if [ $? -eq 0 ]; then
  print_fail
else
  print_ok
fi

if [ -f /usr/local/bin/wg_setup ]; then
  print_check "Checking if the management VPN is alive"
  ping -c1 contestmanager.icpcnet.internal >/dev/null 2>&1
  check_return $?
fi

echo
echo "${BLUE}Compiler Versions${RESET}"
ERLANG_VERSION_OUT=$(erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell 2>/dev/null)
print_version       "ada"       "gnat --version"
print_version       "c"         "gcc --version"
print_version       "cpp"       "g++ --version" "c++"
print_version       "c#"        "mono --version"
print_version       "clojure"   "clojure -e (clojure-version)"
print_version       "dart"      "dart --version"
print_version       "D"         "gdc --version"
print_version       "erlang"    "echo $ERLANG_VERSION_OUT"
print_version       "f#"        "fsharpc"
print_version       "fortran"   "gfortran --version"
print_version       "go"        "go version"
print_version       "gccgo"     "gccgo --version"
print_version       "groovy"    "groovy -version"
print_version       "haskell"   "ghc --version"
print_version       "java"      "java -version"
print_version       "lua"       "lua -v"
print_version       "js"        "nodejs --version"
print_first_version "kotlin"    "kotlin -version"
print_version       "nim"       "nim --version"
print_version       "ocaml"     "ocaml -version"
print_version       "pascal"    "fpc -version"
print_version       "prolog"    "swipl --version"
print_version       "python2"   "python --version"
print_version       "pypy"      "pypy --version"
print_version       "python3"   "python3 --version"
print_first_version "python3"   "pypy3 --version" "pypy3"
print_version       "ruby"      "ruby --version"
print_version       "rust"      "rustc --version"
print_version       "scala"     "scala -version"

echo
echo "${BLUE}Image Details${RESET}"
VERSIONINFO=$(cat /icpc/version 2>/dev/null)
VERSIONDEFAULT="${RED}No version info found!${DEFAULT}"
echo -e "${VERSIONINFO:-$VERSIONDEFAULT}"
