---
- name: Do Everything
  hosts: all
  sudo: yes
  user: imageadmin
  tasks:
    - name: Use local apt mirror
      copy: src=files/sources-local-mirror.list dest=/etc/apt/sources.list backup=yes
    - name: copy pam_environment to make sure the proxy is disabled for icpcadmin(and root)
      copy: src=files/pam_environment dest={{ item }}/.pam_environment
      with_items:
        - /root
        - /home/imageadmin

    - name: copy updated pam sudo config so it reads .pam_environment
      copy: src=files/pam_sudo dest=/etc/pam.d/sudo

    - name: disable fsync for dpkg
      copy: src=files/02-dpkg-no-sync dest=/etc/dpkg/dpkg.cfg.d/02-dpkg-no-sync
    - name: disable apt cache
      copy: src=files/02-fast-apt dest=/etc/apt/apt.conf.d/02-fast-apt

    - name: be sure apt cache is updated
      apt: update_cache=yes
      environment: proxy_env

    - include: 'playbooks/gui.yml'
    - include: 'playbooks/_clean.yml'


    - include: 'playbooks/devel_tools.yml'
    - include: 'playbooks/_clean.yml'
    - include: 'playbooks/compilers.yml'
    - include: 'playbooks/_clean.yml'
    - include: 'playbooks/eclipse.yml'
    - include: 'playbooks/_clean.yml'

    - include: 'playbooks/localweb.yml'

    - include: 'playbooks/icpc.yml'
    - include: 'playbooks/lang_docs.yml'
    - include: 'playbooks/vmtouch.yml'
    - include: 'playbooks/_clean.yml'

    - include: 'playbooks/firewall.yml'

    - include: 'playbooks/system.yml'

    # Copy some build information to the image
    - shell: 'echo "Built on $(date +%Y-%m-%d)\nRevision: $(git rev-list --full-history --all --abbrev-commit | head -1)"\n'
      sudo: false
      register: git_revision
      delegate_to: 127.0.0.1
    - name: copy version info
      copy: content="{{git_revision.stdout}}" dest=/icpc/version

  handlers:
    - include: 'playbooks/handlers.yml'
